# This build file installs npm dependencies and then deploys multiple Apps Script projects using clasp.
steps:
  # Step 1: Install dependencies for all projects.
  # This runs first to ensure any required node_modules are available.
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Install clasp, set up credentials, and deploy all projects.
  # This is a single, combined step to ensure 'clasp' and its credentials persist.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk' # This image has gcloud, node, and npm.
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install clasp globally within this step's container
        echo "Installing clasp..."
        npm install -g @google/clasp

        # Set up clasp credentials from Secret Manager
        # The file will be available in this step's home directory.
        echo "Setting up clasp credentials..."
        gcloud secrets versions access latest --secret="clasp-credentials" > ~/.clasprc.json
        
        echo "Deploying to Google Apps Script projects..."
        PROJECTS=(
          "projects/calendar"
          "projects/chat" 
          "projects/docs"
          "projects/drive"
          "projects/gmail"
          "projects/photos"
          "projects/sheets"
          "projects/slides"
          "projects/tasks"
          "projects/utility"
        )
        
        SUCCESS_COUNT=0
        FAILED_PROJECTS=""
        
        # Loop through each project directory and deploy
        for PROJECT_DIR in "${PROJECTS[@]}"; do
          if [ -d "$PROJECT_DIR" ] && [ -f "$PROJECT_DIR/.clasp.json" ]; then
            echo "📦 Deploying $PROJECT_DIR..."
            (cd "$PROJECT_DIR" && clasp push --force) # Run in a subshell to avoid manual cd back
            
            if [ $? -eq 0 ]; then
              echo "✅ Successfully deployed $PROJECT_DIR"
              SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
            else
              echo "❌ Failed to deploy $PROJECT_DIR"
              FAILED_PROJECTS="$FAILED_PROJECTS $PROJECT_DIR"
            fi
          else
            echo "⚠️ Skipping $PROJECT_DIR (directory or .clasp.json not found)"
          fi
        done
        
        # Print a final summary of the deployment results
        echo "================================================"
        echo "Deployment Summary:"
        echo "✅ Successful deployments: $SUCCESS_COUNT"
        if [ -n "$FAILED_PROJECTS" ]; then
          echo "❌ Failed deployments:$FAILED_PROJECTS"
          echo "================================================"
          exit 1
        else
          echo "🎉 All deployments completed successfully!"
          echo "================================================"
        fi

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
