# Optimized Cloud Build configuration for Google Apps Script deployment
# Combines all clasp operations in a single step to resolve container isolation issues

steps:
  # Single combined step: Install Node.js, clasp, authenticate, and deploy all projects
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit on any error
        
        echo "🚀 Google Apps Script Deployment Pipeline"
        echo "========================================"
        
        # Step 0: Install Node.js and npm in the Cloud SDK container
        echo "📦 Installing Node.js and npm..."
        apt-get update && apt-get install -y nodejs npm
        echo "✅ Node.js installed: $$(node --version)"
        echo "✅ npm installed: $$(npm --version)"
        
        # Step 1: Install clasp globally in this container
        echo "📥 Installing @google/clasp..."
        npm install -g @google/clasp
        echo "✅ Clasp installed: $$(clasp --version)"
        
        # Step 2: Set up authentication using Secret Manager
        echo "🔐 Setting up clasp credentials..."
        gcloud secrets versions access latest \
          --secret="clasp-credentials" \
          --project="workspace-automation-466800" > ~/.clasprc.json
        chmod 600 ~/.clasprc.json
        
        # Verify credentials are valid
        if clasp login --status > /dev/null 2>&1; then
          echo "✅ Clasp authentication successful"
        else
          echo "❌ Clasp authentication failed"
          exit 1
        fi
        
        # Step 3: Deploy all Apps Script projects
        echo "📤 Starting deployment to all projects..."
        echo ""
        
        # Define all project directories
        PROJECTS=(
          "projects/calendar"
          "projects/chat" 
          "projects/docs"
          "projects/drive"
          "projects/gmail"
          "projects/photos"
          "projects/sheets"
          "projects/slides"
          "projects/tasks"
          "projects/utility"
        )
        
        # Deployment tracking
        SUCCESS_COUNT=0
        TOTAL_PROJECTS=0
        FAILED_PROJECTS=""
        
        # Deploy each project
        for PROJECT_DIR in "$${PROJECTS[@]}"; do
          if [ -d "$$PROJECT_DIR" ] && [ -f "$$PROJECT_DIR/.clasp.json" ]; then
            TOTAL_PROJECTS=$$((TOTAL_PROJECTS + 1))
            echo "🔄 Deploying $$PROJECT_DIR..."
            
            # Use subshell to avoid changing working directory permanently
            if (cd "$$PROJECT_DIR" && clasp push --force); then
              echo "✅ $$PROJECT_DIR deployed successfully"
              SUCCESS_COUNT=$$((SUCCESS_COUNT + 1))
            else
              echo "❌ $$PROJECT_DIR deployment failed"
              FAILED_PROJECTS="$$FAILED_PROJECTS $$PROJECT_DIR"
            fi
            echo ""
          else
            echo "⚠️  Skipping $$PROJECT_DIR (missing directory or .clasp.json)"
          fi
        done
        
        # Final deployment report
        echo "========================================"
        echo "📊 DEPLOYMENT SUMMARY"
        echo "========================================"
        echo "Total projects: $$TOTAL_PROJECTS"
        echo "Successful: $$SUCCESS_COUNT"
        echo "Failed: $$((TOTAL_PROJECTS - SUCCESS_COUNT))"
        
        if [ $$SUCCESS_COUNT -eq $$TOTAL_PROJECTS ] && [ $$TOTAL_PROJECTS -gt 0 ]; then
          echo ""
          echo "🎉 ALL DEPLOYMENTS COMPLETED SUCCESSFULLY!"
          echo "========================================"
        elif [ -n "$$FAILED_PROJECTS" ]; then
          echo ""
          echo "❌ Failed projects:$$FAILED_PROJECTS"
          echo "========================================"
          exit 1
        else
          echo ""
          echo "⚠️  No valid projects found to deploy"
          echo "========================================"
          exit 1
        fi

# Build configuration
options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Set reasonable timeout for Node.js installation + deployments
timeout: '900s'  # 15 minutes to account for package installation
