name: Bug Report
description: Report a bug or issue with a script
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: script-name
    attributes:
      label: Script Name
      description: Which script is causing the issue?
      placeholder: "e.g., gmail-export-pdf-markdown.gs"
    validations:
      required: true

  - type: dropdown
    id: service
    attributes:
      label: Google Service
      description: Which Google service is involved?
      options:
        - Gmail
        - Google Drive
        - Google Calendar
        - Google Docs
        - Google Sheets
        - Google Tasks
        - Google Chat
        - Google Slides
        - Multiple Services
        - Utility/Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe what happened and what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. Execute...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Any error messages you received
      placeholder: "Paste error messages here"

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your setup details
      placeholder: |
        - Google Workspace account type (personal/business)
        - Apps Script execution environment
        - Any relevant API permissions
        - Browser (if applicable)

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality
        - High - Prevents script from working
        - Critical - Causes data loss or security issues
    validations:
      required: true

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting Done
      description: What troubleshooting have you already tried?
      options:
        - label: Checked script permissions
        - label: Verified API access
        - label: Tested with different data
        - label: Reviewed error logs
        - label: Checked documentation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
