# Alternative Cloud Build Configuration using official Node.js image
# This avoids the npm permission issues in the custom Docker image
timeout: 1200s
steps:
# Step 1: Install dependencies
- name: 'node:18'
  entrypoint: 'npm'
  args: ['install', '-g', '@google/clasp']

# Step 2: Authenticate and deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -e
      
      # Install Node.js in cloud-sdk container
      apk add --no-cache nodejs npm
      
      # Install clasp
      npm install -g @google/clasp
      
      echo "✅ Environment ready"
      echo "Node.js version: $$(node --version)"
      echo "gcloud version: $$(gcloud --version | head -1)"
      
      # Authenticate and verify credentials
      echo "🔐 Setting up clasp credentials..."
      gcloud secrets versions access latest --secret="clasp-credentials" --project="$PROJECT_ID" > ~/.clasprc.json
      chmod 600 ~/.clasprc.json
      
      # Verify authentication
      if ! /usr/bin/npx clasp login --status > /dev/null 2>&1; then
        echo "❌ Clasp authentication failed. Check the 'clasp-credentials' secret."
        exit 1
      fi
      echo "✅ Clasp authentication successful"

      # Deploy all projects
      echo "📦 Deploying all Google Apps Script projects..."
      PROJECTS=(
        "apps/calendar" "apps/chat" "apps/docs" "apps/drive"
        "apps/gmail" "apps/photos" "apps/sheets" "apps/slides"
        "apps/tasks" "apps/utility"
      )
      
      SUCCESS_COUNT=0
      TOTAL_PROJECTS=0
      FAILED_PROJECTS=""
      
      for PROJECT_DIR in "$${PROJECTS[@]}"; do
        if [ -d "$$PROJECT_DIR" ] && [ -f "$$PROJECT_DIR/.clasp.json" ]; then
          TOTAL_PROJECTS=$$((TOTAL_PROJECTS + 1))
          echo "   -> Deploying $$PROJECT_DIR..."
          if (cd "$$PROJECT_DIR" && /usr/bin/npx clasp push --force); then
            SUCCESS_COUNT=$$((SUCCESS_COUNT + 1))
            echo "   ✅ $$PROJECT_DIR deployed successfully"
          else
            FAILED_PROJECTS="$$FAILED_PROJECTS $$PROJECT_DIR"
            echo "   ❌ $$PROJECT_DIR deployment failed"
          fi
        else
          echo "   ⚠️ Skipping $$PROJECT_DIR (missing directory or .clasp.json)"
        fi
      done
      
      # Report Summary
      echo ""
      echo "================================================="
      echo "📊 DEPLOYMENT SUMMARY"
      echo "================================================="
      echo "Total projects found: $$TOTAL_PROJECTS"
      echo "✅ Successful deployments: $$SUCCESS_COUNT"
      
      if [ $$SUCCESS_COUNT -eq $$TOTAL_PROJECTS ] && [ $$TOTAL_PROJECTS -gt 0 ]; then
        echo ""
        echo "🎉 ALL DEPLOYMENTS COMPLETED SUCCESSFULLY!"
      else
        echo "❌ Failed deployments: $$((TOTAL_PROJECTS - SUCCESS_COUNT))"
        echo "Failed projects:$$FAILED_PROJECTS"
        exit 1
      fi
options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8