#!/bin/bash

# Remove duplicate txt files that already exist in the repository

echo "Removing duplicate txt files..."

cd "/Users/kevinlappe/Documents/GitHub/Workspace Automation"

# Remove exact duplicates of repository files
rm -f "txt to convert/event-export-gcp-distance-time.txt"
rm -f "txt to convert/events-date-duration-time-distance.txt"
rm -f "txt to convert/docs-formatter.txt"
rm -f "txt to convert/drive-docs-finder-by-alias.txt"
rm -f "txt to convert/Index-Docs-Files.txt"
rm -f "txt to convert/Index-MD-Files.txt"
rm -f "txt to convert/v100-drive-index.txt"
rm -f "txt to convert/Index-v10.txt"
rm -f "txt to convert/zzz-yaml-___.txt"
rm -f "txt to convert/linter-md-lines-spacing.txt"
rm -f "txt to convert/Markdown File Mover and Metadata Updater.txt"
rm -f "txt to convert/Drive Markdown Blank Links File Processor.txt"
rm -f "txt to convert/calendar-export-daily-manual.txt"
rm -f "txt to convert/vX-Weekly Daily Notes Creator.txt"
rm -f "txt to convert/Weekly Daily Notes Creator.txt"
rm -f "txt to convert/Weekly Notes Generator.txt"
rm -f "txt to convert/drive-shortcuts-to-shortcuts.txt"
rm -f "txt to convert/yaml-frontmatter-to-drive-folder-files-md.txt"
rm -f "txt to convert/YAML-add-frontmatter-multi-options.txt"
rm -f "txt to convert/zzz-yaml-add-yaml.txt"
rm -f "txt to convert/dataview-category-subcategory-yaml.txt"
rm -f "txt to convert/yaml-folder-category.txt"
rm -f "txt to convert/email-data-24months.txt"
rm -f "txt to convert/email-export-pdf-md-sheets.txt"
rm -f "txt to convert/email-export-to-sheets-search-label0rkeywaord-or-dateRange.txt"
rm -f "txt to convert/email-labels-data.txt"
rm -f "txt to convert/email-md-sheets-yaml-number-1.txt"
rm -f "txt to convert/gmail-meta-24months-misc.txt"
rm -f "txt to convert/gmail-to-docs-pdf-to-sheets.txt"
rm -f "txt to convert/gmail-export-weekly-threads.txt"
rm -f "txt to convert/gmail-label-maker.txt"
rm -f "txt to convert/gmail-labels-analysis.txt"
rm -f "txt to convert/gmail-labels-labeled-not-labeled-count.txt"
rm -f "txt to convert/gmail-labels-maker-sender.txt"
rm -f "txt to convert/gmail-labels-date-processor.txt"
rm -f "txt to convert/gmail-labels-delete-all.txt"
rm -f "txt to convert/gmail-labels-export-to-sheets.txt"
rm -f "txt to convert/gmail-labels-statistics (1).txt"
rm -f "txt to convert/gmail-labels-statistics.txt"
rm -f "txt to convert/gmail-labels-unread-emails.txt"
rm -f "txt to convert/Markdown Header Cleaner.txt"
rm -f "txt to convert/change all gmail to read.txt"
rm -f "txt to convert/Markdown Format Fixer.txt"
rm -f "txt to convert/drive-md-linter.txt"
rm -f "txt to convert/sheets-date-automation-checkbox-rx.txt"
rm -f "txt to convert/sheets-folders-files-indexer.txt"
rm -f "txt to convert/sheets-indexer.txt"
rm -f "txt to convert/tasks-export-tasklist-md-yaml.txt"
rm -f "txt to convert/tasks-md-obsidian-folder.txt"
rm -f "txt to convert/tasks-to-todos-md-folder.txt"
rm -f "txt to convert/yaml-finder.txt"

echo "Removed duplicate txt files"

# Count remaining files
remaining=$(ls "txt to convert/" | wc -l)
echo "Remaining txt files: $remaining"