version: '3.8'

services:
  test-env:
    build: 
      context: ..
      dockerfile: test-environment/Dockerfile
    container_name: gcp-test-environment
    environment:
      # GitHub Actions environment variables
      - GITHUB_SHA=${GITHUB_SHA:-test-sha-123456}
      - GITHUB_REF=${GITHUB_REF:-refs/heads/main}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY:-klappe-pm/Another-Google-Automation-Repo}
      - GITHUB_ACTOR=${GITHUB_ACTOR:-test-user}
      - GITHUB_WORKFLOW=${GITHUB_WORKFLOW:-test-workflow}
      - GITHUB_RUN_ID=${GITHUB_RUN_ID:-123456}
      - GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER:-1}
      - GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME:-push}
      - GITHUB_WORKSPACE=/workspace
      
      # GCP Project settings
      - PROJECT_ID=${PROJECT_ID:-workspace-automation-466800}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-workspace-automation-466800}
      
    volumes:
      - ..:/workspace
      - gcp-config:/root/.config/gcloud
    working_dir: /workspace
    stdin_open: true
    tty: true

volumes:
  gcp-config:
