name: Deploy to Google Cloud
on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/784508074368/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-ci@workspace-automation-466800.iam.gserviceaccount.com'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Run Cloud Build
      run: gcloud builds submit --tag gcr.io/workspace-automation-466800/workspace-automation-latest
