name: Deploy to Google Apps Script
on:
  push:
    branches:
      - main

jobs:
  set-pending-status:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
    - name: Set deployment status to pending
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'pending',
            description: 'Deployment started',
            context: 'deploy/google-apps-script'
          });

  deploy:
    runs-on: ubuntu-latest
    needs: set-pending-status
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'apps/784508074368/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-ci@workspace-automation-466800.iam.gserviceaccount.com'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - name: Dispatch Cloud Build
      run: gcloud builds submit --config .github/workflows/cloudbuild.yml

  set-success-status:
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    permissions:
      statuses: write
    steps:
    - name: Set deployment status to success
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'success',
            description: 'Deployment completed successfully', 
            context: 'deploy/google-apps-script'
          });

  set-failure-status:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    permissions:
      statuses: write
    steps:
    - name: Set deployment status to failure
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'failure',
            description: 'Deployment failed',
            context: 'deploy/google-apps-script'
          });
