name: Deploy to Google Apps Script

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/784508074368/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-ci@workspace-automation-466800.iam.gserviceaccount.com'
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Test Cloud Build
      run: |
        echo "Testing Cloud Build configuration..."
        if [ -f cloudbuild.yaml ]; then
          echo "✅ cloudbuild.yaml exists"
          gcloud builds submit --config=cloudbuild.yaml --dry-run
          echo "✅ Cloud Build configuration is valid"
        else
          echo "❌ cloudbuild.yaml not found"
          exit 1
        fi
        
    - name: Deploy via Cloud Build
      run: |
        echo "Starting Cloud Build deployment..."
        BUILD_ID=$(gcloud builds submit --config=cloudbuild.yaml --format="value(id)")
        echo "Build ID: $BUILD_ID"
        
        # Wait for build completion
        gcloud builds wait $BUILD_ID
        echo "✅ Deployment completed successfully"
