name: GAS Format Check

on:
  pull_request:
    paths:
      - 'apps/**/*.gs'
  workflow_dispatch:
    inputs:
      fix:
        description: 'Auto-fix formatting issues'
        required: false
        default: 'false'
        type: boolean

jobs:
  format-check:
    name: Check Script Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        id: format
        run: |
          # Run formatter in check mode
          node automation/dev-tools/gas-formatter.js --all --check > format-report.txt 2>&1 || true
          
          # Check if any files would be changed
          if grep -q "would be formatted" format-report.txt; then
            echo "needs_formatting=true" >> $GITHUB_OUTPUT
          else
            echo "needs_formatting=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment PR
        if: steps.format.outputs.needs_formatting == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('format-report.txt', 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `⚠️ **Formatting Issues Found**\n\nSome scripts need formatting. Run the following command locally:\n\n\`\`\`bash\nnpm run format:all\n\`\`\`\n\n<details>\n<summary>Formatting Report</summary>\n\n\`\`\`\n${report}\n\`\`\`\n</details>`
            })

      - name: Auto-fix formatting
        if: github.event.inputs.fix == 'true' && steps.format.outputs.needs_formatting == 'true'
        run: npm run format:all

      - name: Create PR with fixes
        if: github.event.inputs.fix == 'true' && steps.format.outputs.needs_formatting == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'style: auto-format Google Apps Scripts'
          title: 'Auto-format Google Apps Scripts'
          body: |
            ## Automated Formatting

            This PR applies automatic formatting to Google Apps Scripts based on the style guide.

            ### Changes Applied
            - Fixed indentation (2 spaces)
            - Added missing headers
            - Fixed spacing issues
            - Added function documentation stubs

            Please review the changes and complete any TODO items in the headers.
          branch: auto-format-scripts
          labels: |
            formatting
            automated