name: Update GAS Catalog

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**/*.gs'
  schedule:
    - cron: '0 9 * * *'  # Daily at 9 AM UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-catalog:
    name: Update Script Catalog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate catalog
        run: |
          npm run catalog
          npm run catalog:json

      - name: Check for changes
        id: check
        run: |
          if git diff --quiet docs/SCRIPT_CATALOG.md docs/script-catalog.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update script catalog'
          title: 'Update Script Catalog'
          body: |
            ## Script Catalog Update

            This PR updates the script catalog with the latest changes:
            - Updated script metadata
            - Recalculated documentation scores
            - Added new scripts (if any)

            ### Files Updated
            - `docs/SCRIPT_CATALOG.md` - Human-readable catalog
            - `docs/script-catalog.json` - Machine-readable catalog

            *This PR was automatically generated by the GAS Catalog workflow.*
          branch: update-script-catalog
          delete-branch: true
          labels: |
            documentation
            automated

      - name: Auto-merge PR
        if: steps.check.outputs.changed == 'true'
        uses: pascalgn/merge-action@v0.15.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "automated"
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: "true"