name: Manual Status Management

on:
  workflow_call:
    inputs:
      status:
        description: 'Status to set (pending, success, failure, error)'
        required: true
        type: string
      description:
        description: 'Status description'
        required: false
        type: string
        default: ''
      context:
        description: 'Status context'
        required: false
        type: string
        default: 'ci/github-actions'
      target_url:
        description: 'Target URL for the status'
        required: false
        type: string
        default: ''

jobs:
  set-status:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set commit status
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        STATUS="${{ inputs.status }}"
        DESCRIPTION="${{ inputs.description }}"
        CONTEXT="${{ inputs.context }}"
        TARGET_URL="${{ inputs.target_url }}"
        SHA="${{ github.sha }}"
        REPO="${{ github.repository }}"
        
        echo "Setting status: $STATUS for commit $SHA"
        
        # Create JSON payload
        JSON_PAYLOAD="{\"state\":\"$STATUS\",\"description\":\"$DESCRIPTION\",\"context\":\"$CONTEXT\""
        if [ -n "$TARGET_URL" ]; then
          JSON_PAYLOAD="$JSON_PAYLOAD,\"target_url\":\"$TARGET_URL\""
        fi
        JSON_PAYLOAD="$JSON_PAYLOAD}"
        
        # Set the commit status
        echo "$JSON_PAYLOAD" | gh api \
          --method POST \
          --header "Accept: application/vnd.github+json" \
          "/repos/$REPO/statuses/$SHA" \
          --input -
          
        echo "✅ Status updated successfully"
