name: Test GitHub Secrets

# This is a temporary workflow to test that required secrets are properly configured
# Can be removed after successful verification

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-secrets.yml'  # Only run when this file changes

jobs:
  test-secrets:
    name: Test Required Secrets
    runs-on: ubuntu-latest
    
    # Configure OIDC permissions for GCP authentication
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test GCP OIDC Authentication
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Verify GCP Authentication
        run: |
          echo "Testing GCP authentication..."
          gcloud auth login --brief
          echo "✅ GCP OIDC authentication successful"
          
          # Show authenticated account (without sensitive details)
          echo "Authenticated as:"
          gcloud config get-value account
          
          # Test basic GCP access
          echo "Testing GCP project access..."
          gcloud config get-value project || echo "No default project set"

      - name: Install Snyk
        run: |
          echo "Installing Snyk CLI..."
          npm install -g snyk

      - name: Test Snyk Authentication
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          echo "Testing Snyk authentication..."
          snyk auth $SNYK_TOKEN
          echo "✅ Snyk authentication successful"
          
          # Test Snyk access (without exposing sensitive info)
          echo "Testing Snyk access..."
          snyk test --dry-run . || echo "Snyk test command available"

      - name: Test Optional CLASP Token (if present)
        if: ${{ secrets.CLASP_OAUTH_TOKEN != '' }}
        env:
          CLASP_OAUTH_TOKEN: ${{ secrets.CLASP_OAUTH_TOKEN }}
        run: |
          echo "CLASP OAuth token is present"
          echo "✅ CLASP_OAUTH_TOKEN secret is configured"

      - name: Summary
        run: |
          echo "🎉 Secret verification complete!"
          echo ""
          echo "✅ GCP_WORKLOAD_ID_PROVIDER: Configured and working"
          echo "✅ GCP_SERVICE_ACCOUNT: Configured and working"
          echo "✅ SNYK_TOKEN: Configured and working"
          
          if [ -n "${{ secrets.CLASP_OAUTH_TOKEN }}" ]; then
            echo "✅ CLASP_OAUTH_TOKEN: Configured (optional)"
          else
            echo "ℹ️  CLASP_OAUTH_TOKEN: Not configured (optional)"
          fi
          
          echo ""
          echo "All required GitHub secrets are properly configured!"
          echo "You can now safely remove this test workflow."
